#!/usr/bin/bash

# run this php command as correct user to fix permission issues in docker exec
# docker exec does run as root by default

# enables xdebug for the time this script is running
INI_PATH=/etc/php/8.2/cli/conf.d/99-phpunit.ini
printf 'zend_extension=xdebug.so\nxdebug.mode=coverage\nmemory_limit=-1' > $INI_PATH

NGINX_USERNAME=$(stat -L -c %U /framelix/userdata/)
su $NGINX_USERNAME -s /usr/bin/php  -- "$@"

RESULT=$?

rm -f $INI_PATH

exit $RESULT