#!/usr/bin/bash

while getopts "y" opt; do
    case $opt in
    y)
      echo -n "Drop and recreate database ... "
      mysql -u root -papp -e "DROP DATABASE app; CREATE DATABASE app;"
      echo "Done"
      echo -n "Remove configs ... "
      rm /framelix/userdata/*/private/config/01-core.php
      rm /framelix/userdata/*/private/config/02-ui.php
      echo "Done"
      echo "All finished"
      exit
    esac
done

echo "Database 'app' will be deleted and recreated, app default configs will be deleted as well. Use -y parameter to proceed."
