volumes:
    mariadb:
      name: ${COMPOSE_PROJECT_NAME}_mariadb
    postgres:
      name: ${COMPOSE_PROJECT_NAME}_postgres

services:
  mariadb:
    image: docker.io/mariadb:lts
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=app
      - MARIADB_USER=app
      - MARIADB_PASSWORD=app
      - MARIADB_AUTO_UPGRADE=1
    healthcheck:
      test: mariadb -u root '-papp' -e '\q'
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    image: docker.io/postgres:latest
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=app
    healthcheck:
      test: psql -U postgres -c '\q'
      interval: 5s
      timeout: 5s
      retries: 5
  playwright:
    image: mcr.microsoft.com/playwright:v1.51.0-noble
    restart: on-failure
    volumes:
      - ../appdata:/framelix/appdata
      - ../userdata:/framelix/userdata
    ipc: host
    command: sleep infinity
    environment:
      - FRAMELIX_MODULES=${FRAMELIX_MODULES}"
    network_mode: "host"
  app:
    image: ${USE_IMAGE_NAME}
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ../appdata:/framelix/appdata
      - ../userdata:/framelix/userdata
    ports:
      - "127.0.0.1:${FRAMELIX_TEST_PORT}:${FRAMELIX_TEST_PORT}"
      - "127.0.0.1:${FRAMELIX_DOCS_PORT}:${FRAMELIX_DOCS_PORT}"
      - "127.0.0.1:${FRAMELIX_STARTER_PORT}:${FRAMELIX_STARTER_PORT}"
      - "127.0.0.1:${FRAMELIX_DEMO_PORT}:${FRAMELIX_DEMO_PORT}"
    environment:
      - FRAMELIX_MODULES=${FRAMELIX_MODULES}"
      - FRAMELIX_DEVMODE=${FRAMELIX_DEVMODE}"