version: "3.4"

networks:
  app:
    driver: bridge


volumes:
    mariadb:
      name: ${COMPOSE_PROJECT_NAME}_mariadb

services:
  mariadb:
    image: mariadb:10.11
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - COMPOSE_PROJECT_NAME
      - MARIADB_ROOT_PASSWORD=app
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --connect
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: ${USE_IMAGE_NAME}
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ../appdata:/framelix/appdata
      - ../userdata:/framelix/userdata
    ports:
      - "${FRAMELIX_TEST_PORT}:${FRAMELIX_TEST_PORT}"
      - "${FRAMELIX_DOCS_PORT}:${FRAMELIX_DOCS_PORT}"
      - "${FRAMELIX_STARTER_PORT}:${FRAMELIX_STARTER_PORT}"
    environment:
      - COMPOSE_PROJECT_NAME
      - FRAMELIX_MODULES
      - FRAMELIX_DEVMODE