version: "3"

name: framelix_tests

networks:
  app:
    driver: bridge


volumes:
  framelix_tests_vol:

services:
  app:
    build: ..
    restart: on-failure
    volumes:
      - framelix_tests_vol:/framelix/dbdata
      - ../appdata:/framelix/appdata
      - ../userdata:/framelix/userdata
    ports:
      - "${FRAMELIX_PUBLICPORT}:${FRAMELIX_PUBLICPORT}"
    environment:
      - COMPOSE_PROJECT_NAME
      - FRAMELIX_MODULES
      - FRAMELIX_UNIT_TESTS
      - FRAMELIX_DEVMODE