version: "3.4"

networks:
  app:
    driver: bridge

volumes:
  vol:
    external: true
    name: ${DOCKER_CONTAINER_NAME}_vol

services:
  app:
    build: ..
    restart: on-failure
    volumes:
      - ../appdata:/framelix/appdata
      - vol:/framelix/dbdata
      - ../userdata:/framelix/userdata
    ports:
      - "${FRAMELIX_PUBLICPORT}:${FRAMELIX_PUBLICPORT}"
    environment:
      - COMPOSE_PROJECT_NAME
      - FRAMELIX_MODULES=${FRAMELIX_MODULES}
      - FRAMELIX_UNIT_TESTS
      - FRAMELIX_PLAYWRIGHT_TESTS